config/routes.rb
Rails.application.routes.draw do
  resources :genres
  resource :session

	get 'signup' => 'users#new'	  
  get 'signin' => 'sessions#new'
  # get 'movies/filter/hits' => "movies#index", scope: "hits"
  # get 'movies/filter/flops' => "movies#index", scope: "flops"  

  get 'movies/filter/:scope' => "movies#index", as: :filtered_movies

  resources :users

	root 'movies#index'

	resources :movies do
		resources :reviews
    resources :favorites    
	end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :favorites, dependent: :destroy
	has_many :fans, through: :favorites, source: :user

	has_many :characterizations, dependent: :destroy
	has_many :genres, through: :characterizations

	validates :title, :released_on, :duration, presence: true

	validates :description, length: { minimum: 25 }

	validates :total_gross, numericality: { greater_than_or_equal_to: 0 }

	validates :image_file_name, allow_blank: true, format: {
		with: /\w+\.(gif|jpg|png)\z/i,
		message: "must reference a GIF, JPG, or PNG image"		
	}

	has_many :reviews, dependent: :destroy

	RATINGS = %w(G PG PG-13 R NC-17)
	validates :rating, inclusion: { in: RATINGS }

	scope :released, -> { where("released_on <= ?", Time.now).order(released_on: :desc) }
	scope :hits, -> { released.where('total_gross >= 300000000').order(total_gross: :desc) }
	scope :flops, -> { released.where('total_gross < 500000000').order(total_gross: :asc) }
	scope :upcoming, -> { where('released_on > ?', Time.now).order(released_on: :asc) }
	scope :rated, ->(rating) { released.where(rating: rating) }
	scope :recent, ->(max=5) { released.limit(max) }

	def flop?
		total_gross.blank? || total_gross < 50000000
	end

	# def self.released
	# 	where("released_on <= ?", Time.now).order("released_on desc")
	# end

	def average_stars
		reviews.average(:stars)
	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :require_signin, except: [:index, :show]
	before_action :require_admin, except: [:index, :show]

	def index
		case params[:scope]
		when "hits"
			@movies = Movie.hits
		when "flops"
			@movies = Movie.flops
		when "upcoming"
			@movies = Movie.upcoming
		when "recent"
			@movies = Movie.recent
		else
			@movies = Movie.released
		end
	end

	def show
		@movie = Movie.find(params[:id])
		@fans = @movie.fans
		@genres = @movie.genres

		if current_user
			@current_favorite = current_user.favorites.find_by(movie_id: @movie.id)
		end
	end

	def edit
		@movie = Movie.find(params[:id])
	end

	def update
		@movie = Movie.find(params[:id])
		if @movie.update(movie_params)
			redirect_to @movie, notice: "Movie successfully updated!"
		else
			render :edit
		end
	end

	def new
		@movie = Movie.new
	end

	def create
		@movie = Movie.new(movie_params)
		if @movie.save
			redirect_to @movie, notice: "Move successfully created!"
		else
			render :new
		end
	end

	def destroy
		@movie = Movie.find(params[:id])
		@movie.destroy
		redirect_to movies_url, alert: "Movie successfully deleted!"
	end


	private

		def movie_params
		params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross, :cast, :director, :duration, :image_file_name)
		end

end

app/helpers/movies_helper.rb
module MoviesHelper
	
	def format_total_gross(movie)
		if movie.flop?
			content_tag(:strong, 'Flop!')
		else
			number_to_currency(movie.total_gross)
		end
	end

	def image_for(movie)
		if movie.image_file_name.blank?
			image_tag('bug.png')
		else
			image_tag(movie.image_file_name, :size => "120x120")
		end
	end
	
	def format_average_stars(movie)
		if movie.average_stars.nil?
				content_tag(:strong, 'No Reviews')
		else
			pluralize(number_with_precision(movie.average_stars, precision: 1), 'stars')
		end
	end
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>

		<%= render "shared/errors", object: @movie %>
		
		<fieldset>
		<p>
			<%= f.label :title %><br/>
			<%= f.text_field :title, autofocus: true %>
		</p>
		<p>
			<%= f.label :description %><br/>
			<%= f.text_area :description, cols: 40, rows: 8 %>
		</p>
		<p>
			<%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name) %>
		</p>
		<p>
			<%= f.label :rating %><br/>
			<%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>
		</p>
		<p>
			<%= f.label :released_on %><br/>
			<%= f.date_select :released_on %>
		</p>
		<p>
			<%= f.label :total_gross %><br/>
			<%= f.number_field :total_gross %>
		</p>
		<p>
			<%= f.label :cast %><br/>
			<%= f.text_field :cast %>
		</p>	
		<p>
			<%= f.label :director %><br/>
			<%= f.text_field :director %>
		</p>
		<p>
			<%= f.label :duration %><br/>
			<%= f.text_field :duration, size: 10 %>
		</p>		
		<p>
			<%= f.label :image_file_name %><br/>
			<%= f.text_field :image_file_name %>
		</p>
		<p>
			<%= f.submit %> |
			<%= link_to "Cancel", movies_path %>
		</p>
		</fieldset>

<% end %>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<%= render 'form' %>

app/views/movies/index.html.erb
<h1><%= pluralize(@movies.size, 'Movie') %></h1>

<% @movies.each do |movie| %>
  <article class="movie">
    <header>
      <h2><%= link_to movie.title, movie_path(movie) %></h2>
      <%= image_for(movie) %>
      <h3><%= movie.cast %></h3>
    </header>
    <p>
      <%= truncate(movie.description, length: 40, separator: ' ') %>
    </p>
    <table>
      <tr>
        <th>Released:</th>
        <td><%= movie.released_on %></td>
      </tr>
      <tr>
        <th>Rating:</th>
        <td><%= movie.rating %></td>
      </tr>
      <tr>
        <th>Total Gross:</th>
<!--         <td><%= number_to_currency(movie.total_gross) %></td> -->
             <td><%= format_total_gross(movie) %></td>
      </tr>
      <tr>
        <th>Duration:</th>
        <td><%= movie.duration %></td>
      </tr>
    </table>
  </article>
<% end %>

app/views/movies/new.html.erb
<h1>Create New Movie</h1>

<%= render 'form' %>

app/views/movies/show.html.erb
<% title("#{@movie.title} (#{@movie.released_on.year})") %>

<h2>Title: <%= @movie.title %> </h2>

<h3>Description</h3>
<p>
	<%= @movie.description %>
</p>
<h3>Rating</h3>
<p>
	<%= @movie.rating %>
</p>
<% content_for :side do %>
	<h3>Genres</h3>
	<ul>
		<% @genres.each do |genre| %>
			<li><%= genre.name %></li>
		<% end %>
	</ul>

	<% if @fans.any? %>
	<h3>Fans' Favorites</h3>
	<% if current_user %>
		<% if @current_favorite %>
			<%= button_to "Unfave", movie_favorite_path(@movie, @current_favorite), method: :delete, class: "button unfave" %>
		<% else %>
			<%= button_to "Fave", movie_favorites_path(@movie), class: "button fave" %>
		<% end %>	
	<% end %>

<% end %>
<p>
	<%= pluralize(@fans.size, 'fan') %>
</p>	
	<ul>
		<% @fans.each do |user| %>
			<li>
				<%= link_to user.name, user %>
			</li>
		<% end %>
	</ul>
<% end %>
<h3>Release</h3>
<p>
	<%= @movie.released_on %>
</p>
<h3>Total Gross</h3>
<p>
	<%= format_total_gross(@movie) %>
</p>

<h3>Cast</h3>
<p>
	<%= @movie.cast %>
</p>
<h3>Director</h3>
<p>
	<%= @movie.director %>
</p>
<h3>Duration</h3>
<p>
	<%= @movie.duration %>
</p>
<h3>Average Review</h3>
<p>
	<%= format_average_stars(@movie) %>
</p>

<h3>Reviews</h3>
<p>
	<%= link_to pluralize(@movie.reviews.size, "review"),
								movie_reviews_path(@movie) %>
</p>

<footer>
	<%= link_to "Write Review", new_movie_review_path(@movie),
							class: 'button ok review' %>

	<nav>
		<% if current_user_admin? %>
		<%= link_to "Edit", edit_movie_path(@movie), class: 'button' %> |
		<%= link_to "Delete", @movie, 
								class: 'button',
								method: :delete, date: { confirm: 'Delete confirm?' } %>
		<% end %>
	</nav>
</footer>