config/routes.rb
Rails.application.routes.draw do
  resources :genres
  resource :session

	get 'signup' => 'users#new'	  
  get 'signin' => 'sessions#new'
  # get 'movies/filter/hits' => "movies#index", scope: "hits"
  # get 'movies/filter/flops' => "movies#index", scope: "flops"  

  get 'movies/filter/:scope' => "movies#index", as: :filtered_movies

  resources :users

	root 'movies#index'

	resources :movies do
		resources :reviews
    resources :favorites    
	end

end

app/views/layouts/_footer.html.erb
<footer id="page-footer">
	<p>
		Copyright &copy; 2015
		<%= link_to 'The Pragmatic Studio', 'http://pragmaticstudio.com' %>
	</p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
	<div id="masthead">
		<h1><%= link_to "Super-Heroic Flix", root_path %></h1>
		<nav>
			<p>
				<% if current_user %>
					<%= link_to current_user.name, current_user %>
					<%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %>
					<%= link_to "Account Settings", edit_user_path(current_user) %>
				<% else %>
					<%= link_to 'Sign Up', signup_path, class: 'button' %>
					<%= link_to 'Sign In', signin_path, class: 'button' %>
				<% end %>
			</p>
		</nav>
	</div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
	<nav>
		<ul>
			<li>
				<%= link_to 'Released', movies_path %>
			</li>
			<% if current_user_admin? %>
				<li class="create-movie">
					<%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
				</li>
			<% end %>
			<li class="movies">
				<%= link_to 'Hits', filtered_movies_path(:hits), class: 'button' %>			
			</li>
			<li class="movies">
				<%= link_to 'Flops', filtered_movies_path(:flops), class: 'button' %>
			</li>
			<li class="movies">
				<%= link_to 'Recent', filtered_movies_path(:recent), class: 'button' %>
			</li>			
			<li class="movies">
				<%= link_to 'Upcoming', filtered_movies_path(:upcoming), class: 'button' %>			
			</li>
		</ul>
	</nav>
	<%= content_for(:side) %>	
</aside>	

app/views/layouts/_siderbar.html.erb
<aside style="float: right; background: #F0F0F0; width: 200px;">
	<nav>
		<ul>
			<li>
				<%= link_to 'All Movies', movies_path %>
			</li>
			<li>
				<%= link_to 'Add New Movie', new_movie_path %>
			</li>
		</ul>
	</nav>
</aside>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= page_title %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
<%= render 'layouts/header' %>
	
	<% if flash[:notice] %>
		<p class="flash notice">
			<%= flash[:notice] %>
		</p>
	<% end %>

	<% if flash[:alert] %>
		<p class="flash alert">
			<%= flash[:alert] %>
		</p>
	<% end %>

	<div id="container">
		<%= render 'layouts/sidebar' %>
			<%= yield %>
			<%= render 'layouts/footer' %>	
	</div>
</div>

</body>
</html>